### ISSUE TITLE
 ErrorException: Fatal Error: Method XF\Widget\WidgetRenderer::__toString() must not throw an exception, caught Error: Call to undefined method XF\Entity\User::canViewDailyStatistics() src/XF/Template/Templater.php:0 

### ISSUE THREAD

**Issue by kickdev** [Xon/XenForo2-DailyStatistics#1]
ErrorException: Fatal Error: Method XF\Widget\WidgetRenderer::__toString() must not throw an exception, caught Error: Call to undefined method XF\Entity\User::canViewDailyStatistics() src/XF/Template/Templater.php:0 

#0 [internal function]: XF::handleFatalError()
#1 {main}

array(4) {
  ["url"] => string(1) "/"
  ["referrer"] => bool(false)
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}

**Comment by Xon** [comment]
This isn't a bug with this add-on, but a design flaw where XF disables the add-on code from running during upgrades but leaves the templates in place
